config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(tasks_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<!-- <form action="/tasks/<%= @task.id %>" method="post">
  <input type="hidden" name="_method" value="patch" />
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="name">Title: </label>
  <input type="text" name="task[title]" id="name" value="<%= @task.title %>">

  <label for="address">Details: </label>
  <input type="text" name="task[details]" id="address" value="<%= @task.details %>">

  <label for="address">Completed: </label>
  <input type="text" name="task[completed]" id="address" value="<%= @task.completed %>">

  <input type="submit">
</form>

 -->

 <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>


  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1><strong>My Tasks</strong></h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <p><%= link_to task.title, task_path(task) %></p><p><%= task.details %></p>
      <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a task", tasks_new_path  %>

app/views/tasks/new.html.erb
<!-- <form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="name">Title: </label>
  <input type="text" name="task[title]" id="name">

  <label for="address">Details: </label>
  <input type="text" name="task[details]" id="address">

  <input type="submit">
</form> -->

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Edit", edit_task_path(@task)  %>
<%= link_to "Go back to task list",  tasks_path %>